### ISSUE TITLE
关于剪刀石头布游戏

### ISSUE THREAD

**Issue by BastKakrolot** [dearDreamWeb/long-road#1]
可以适当增加动效，玩家选了三个后直接弹出结果，有点没有太多次参与感
上半部分是老王进行滚动出招
下半部分有玩家选择
玩家选择后给出战果
分三次完成
还可以添加老王进行耍赖的分支
<img width="198" alt="image" src="https://github.com/dearDreamWeb/long-road/assets/45719798/d3e482bd-a745-4c4b-83b7-1c9b34bb7165">

**Comment by dearDreamWeb** [comment]
好主意，这两天有时间搞一下

**Comment by dearDreamWeb** [comment]
石头剪刀布已经改版重做完成了，发布到线上了。
